### PR TITLE
Update readme on deployment

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @openshift/openshift-team-developer-productivity-test-platform 

/hold 

will test when https://github.com/openshift/release/pull/5982 merges

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold cancel

```
$ oc get pod -n ci --kubeconfig build01.config  | grep -v ttl
NAME                                   READY   STATUS      RESTARTS   AGE
33b1508a-0a49-11ea-b401-0a58ac106e48   0/2     Completed   0          56m
33b521e1-0a49-11ea-b401-0a58ac106e48   0/2     Completed   0          56m
b9500f9d-0a4e-11ea-9ba4-0a58ac105f3f   0/2     Completed   0          16m
b95206f0-0a4e-11ea-9ba4-0a58ac105f3f   0/2     Completed   0          16m
b95307b6-0a4e-11ea-9ba4-0a58ac105f3f   0/2     Completed   0          16m
b954060d-0a4e-11ea-9ba4-0a58ac105f3f   0/2     Completed   0          16m
b954dab9-0a4e-11ea-9ba4-0a58ac105f3f   0/2     Completed   0          16m
b957236e-0a4e-11ea-9ba4-0a58ac105f3f   0/2     Completed   0          16m

```

**Review by stevekuznetsov — APPROVED** [review]

**Comment by hongkailiu** [comment]
Missing configmaps "prow-job-cluster-launch-installer-e2e" and secrets "cluster-secrets-aws":

```
Events:
  Type     Reason       Age                     From                                   Message
  ----     ------       ----                    ----                                   -------
  Normal   Scheduled    9m42s                   default-scheduler                      Successfully assigned ci/1ade7ca4-0af8-11ea-9e45-0a58ac106e59 to ip-10-0-173-241.ec2.internal
  Warning  FailedMount  3m28s (x11 over 9m41s)  kubelet, ip-10-0-173-241.ec2.internal  MountVolume.SetUp failed for volume "cluster-profile" : secrets "cluster-secrets-aws" not found
  Warning  FailedMount  3m6s (x3 over 7m39s)    kubelet, ip-10-0-173-241.ec2.internal  Unable to mount volumes for pod "1ade7ca4-0af8-11ea-9e45-0a58ac106e59_ci(26e298bb-0af8-11ea-ab19-12ed1af217fe)": timeout expired waiting for volumes to attach or mount for pod "ci"/"1ade7ca4-0af8-11ea-9e45-0a58ac106e59". list of unmounted volumes=[cluster-profile job-definition]. list of unattached volumes=[apici-ci-operator-credentials cluster-profile job-definition sentry-dsn logs tools gcs-credentials ci-operator-token-n7z92]
  Warning  FailedMount  87s (x12 over 9m41s)    kubelet, ip-10-0-173-241.ec2.internal  MountVolume.SetUp failed for volume "job-definition" : configmaps "prow-job-cluster-launch-installer-e2e" not found

```
Fix CM: https://github.com/openshift/release/pull/6003
Copy secret to build01 manually.

**Comment by hongkailiu** [comment]
blocked by https://coreos.slack.com/archives/GB7NB0CUC/p1574190439342000

**Comment by hongkailiu** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-secret-mirroring-controller/15/pull-ci-openshift-ci-secret-mirroring-controller-master-e2e-aws-build01/16

Passed.

**Review by stevekuznetsov — APPROVED** [review]

**Comment by hongkailiu** [comment]
Need to set this up ... UI approval ... on it now

**Pull request merged**
