### PR TITLE
Generate version file at build time

### PR DESCRIPTION
**Pull request by hongkailiu**
/assign @stevekuznetsov 
Last attempt. ^_^
Just want see if we can <title_above>.

### CODE REVIEW

**Comment by hongkailiu** [comment]
https://github.com/openshift/release/pull/4616

**Comment by hongkailiu** [comment]
retest after https://github.com/openshift/release/pull/4616 is merged.

**Comment by stevekuznetsov** [comment]
Why do we need this? If we're using the `Build` to create the image, we can get the version like:

```
$ docker inspect registry.svc.ci.openshift.org/ci/ci-secret-mirroring-controller:latest | jq '.[0].Config.Labels["io.openshift.build.commit.id"]' --raw-output
8ab3982827d7640b90d85d6bb87c2142de489a71
```

**Comment by hongkailiu** [comment]
> Why do we need this? If we're using the `Build` to create the image, we can get the version like:
> 
> ```
> $ docker inspect registry.svc.ci.openshift.org/ci/ci-secret-mirroring-controller:latest | jq '.[0].Config.Labels["io.openshift.build.commit.id"]' --raw-output
> 8ab3982827d7640b90d85d6bb87c2142de489a71
> ```

Thanks. Good to know.

**Pull request closed without merging**
